"""Rule Daemon — watches L3 persona and L2 scenario files, compiles rules.

Monitors `data/vault/persona/` and `data/vault/scenarios/` for changes.
When files change, extracts rules and writes a compiled `rules.md` that
can be injected into the LLM system prompt.

Usage:
    python -m daemon.rule_daemon [--vault-root PATH] [--interval SECONDS]
"""

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path
from typing import Any


def file_hash(path: Path) -> str:
    """Compute SHA-256 hash of a file."""
    h = hashlib.sha256()
    try:
        h.update(path.read_bytes())
    except OSError:
        return ""
    return h.hexdigest()


def scan_directory(dir_path: Path, extensions: list[str]) -> dict[str, str]:
    """Scan directory and return {filename: hash} for matching extensions."""
    result = {}
    if not dir_path.exists():
        return result
    for f in dir_path.iterdir():
        if f.is_file() and f.suffix in extensions:
            result[f.name] = file_hash(f)
    return result


def extract_rules_from_persona(persona_path: Path) -> list[str]:
    """Extract rules from a YAML/JSON persona file."""
    rules = []
    try:
        import yaml
        with open(persona_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if isinstance(data, dict):
            for rule in data.get("core_rules", []):
                rules.append(f"- {rule}")
            for constraint in data.get("constraints", []):
                rules.append(f"- [CONSTRAINT] {constraint}")
    except Exception as e:
        rules.append(f"- [ERROR parsing {persona_path.name}: {e}]")
    return rules


def extract_rules_from_scenarios(scenarios_dir: Path) -> list[str]:
    """Extract conditional rules from scenario markdown files."""
    rules = []
    if not scenarios_dir.exists():
        return rules

    for md_file in scenarios_dir.glob("*.md"):
        try:
            content = md_file.read_text(encoding="utf-8")
            # Extract conditions from YAML frontmatter
            if content.startswith("---"):
                parts = content.split("---", 2)
                if len(parts) >= 3:
                    import yaml
                    fm = yaml.safe_load(parts[1])
                    if isinstance(fm, dict):
                        conditions = fm.get("conditions", [])
                        for cond in conditions:
                            rules.append(f"- [{md_file.stem}] {cond}")
        except Exception as e:
            rules.append(f"- [ERROR parsing {md_file.name}: {e}]")
    return rules


def compile_rules(vault_root: Path) -> str:
    """Compile all rules from L3 persona and L2 scenarios into markdown."""
    lines = [
        "# Compiled Rules",
        "",
        "Auto-generated by Rule Daemon. Do not edit manually.",
        "",
        "## Core Rules (L3 Persona)",
        "",
    ]

    persona_dir = vault_root / "persona"
    for persona_file in persona_dir.glob("*.yaml"):
        rules = extract_rules_from_persona(persona_file)
        lines.extend(rules)

    for persona_file in persona_dir.glob("*.json"):
        rules = extract_rules_from_persona(persona_file)
        lines.extend(rules)

    lines.extend([
        "",
        "## Conditional Rules (L2 Scenarios)",
        "",
    ])

    scenarios_dir = vault_root / "scenarios"
    rules = extract_rules_from_scenarios(scenarios_dir)
    if rules:
        lines.extend(rules)
    else:
        lines.append("(no scenario rules found)")

    lines.append("")
    return "\n".join(lines)


class RuleDaemon:
    """Watches vault directories and recompiles rules on change."""

    def __init__(self, vault_root: str, interval: float = 2.0):
        self.vault_root = Path(vault_root)
        self.interval = interval
        self.output_path = self.vault_root / "rules.md"
        self._last_hashes: dict[str, str] = {}

    def _snapshot(self) -> dict[str, str]:
        """Take a hash snapshot of all watched files."""
        snapshot = {}
        persona_dir = self.vault_root / "persona"
        scenarios_dir = self.vault_root / "scenarios"
        snapshot.update(scan_directory(persona_dir, [".yaml", ".json"]))
        snapshot.update(scan_directory(scenarios_dir, [".md"]))
        return snapshot

    def _has_changed(self) -> bool:
        """Check if any watched file has changed."""
        current = self._snapshot()
        changed = current != self._last_hashes
        if changed:
            self._last_hashes = current
        return changed

    def run_once(self) -> bool:
        """Run one check cycle. Returns True if rules were recompiled."""
        if self._has_changed():
            rules_md = compile_rules(self.vault_root)
            self.output_path.write_text(rules_md, encoding="utf-8")
            print(f"[RuleDaemon] Rules recompiled → {self.output_path}", file=sys.stderr)
            return True
        return False

    def run_forever(self):
        """Run the daemon loop until interrupted."""
        print(f"[RuleDaemon] Watching {self.vault_root} every {self.interval}s", file=sys.stderr)
        print(f"[RuleDaemon] Output: {self.output_path}", file=sys.stderr)

        # Initial compile
        self._last_hashes = self._snapshot()
        rules_md = compile_rules(self.vault_root)
        self.output_path.write_text(rules_md, encoding="utf-8")
        print(f"[RuleDaemon] Initial rules compiled.", file=sys.stderr)

        try:
            while True:
                time.sleep(self.interval)
                self.run_once()
        except KeyboardInterrupt:
            print("\n[RuleDaemon] Stopped.", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="FourDMem Rule Daemon")
    parser.add_argument(
        "--vault-root",
        default="data/vault",
        help="Path to the vault root directory (default: data/vault)",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=2.0,
        help="Polling interval in seconds (default: 2.0)",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Run once and exit (don't start daemon loop)",
    )
    args = parser.parse_args()

    daemon = RuleDaemon(args.vault_root, args.interval)

    if args.once:
        daemon.run_once()
    else:
        daemon.run_forever()


if __name__ == "__main__":
    main()
